# Generated by Django 3.1.1 on 2020-09-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cartitem_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='user',
        ),
    ]
